### ISSUE TITLE
Launch tracking

### ISSUE THREAD

**Issue by kytrinyx** [exercism/qsharp#1]
Edit this issue to keep track of the tasks you're working on towards launch.

We have a rough guide for how to launch a track, which is sorely outdated but
quite possibly better than nothing (I'm so sorry, I'm waaaay behind on getting
documentation updated).
https://github.com/exercism/legacy-docs/blob/main/language-tracks/launch/README.md

Check out https://github.com/orgs/exercism/teams/track-maintainers/discussions/1
for details about the #maintaining-\<track\> channels and private #maintainers channel in the exercism-team Slack workspace.

Please ask if you have any questions or if anything is confusing!

**Comment by iHiD** [comment]
@kytrinyx Thanks :)
@erikschierboom I guess this repo needs updating to v3 spec. Maybe we get this one correct, then can do the same PR for the the request-language-track repo?

**Comment by ErikSchierboom** [comment]
Will do.

**Comment by iHiD** [comment]
@lynnlangit In case you missed this, we created you a repo to get started in :)

You might like to schedule a chat with @ErikSchierboom to get started. You can email him at erik@exercism.org if so 🙂

**Comment by lynnlangit** [comment]
@iHiD - thanks much! FYI, I am coordinating with the MSFT Q# language team on this track (similar to what I did for the Ballerina track).  I'll keep you all updated as I make progress).

**Comment by iHiD** [comment]
Brilliant. Let me know if/how I can help :)
